CC=g++
CFLAGS=-Wall -std=c++11

all:
	$(CC) $(CFLAGS) main.cpp FGame.cpp FCharacter.cpp FEngine.cpp FLevel.cpp FObject.cpp FVector.cpp FWeapon.cpp FProjectile.cpp FPowerup.cpp FTile.cpp FEffect.cpp -lsfml-graphics -lsfml-window -lsfml-system
clean:
	rm -f *.o FightR2